name: measurements_repository
description: Repository responsible for handling user fitness entries
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  database_client:
    path: ../database_client
  equatable: ^2.0.3
  rxdart: ^0.27.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
